export const prospectMapping = [
    ['id', 'prospectId', 'number'],
    ['company_name', 'companyName', 'string'],
    ['first_name', 'firstName', 'string'],
    ['last_name', 'lastName', 'string'],
    ['job_title', 'jobTitle', 'string'],
    ['email', 'emailAddress', 'string'],
    ['phone', 'phoneNumber', 'string'],
    ['city', 'city', 'string'],
    ['state', 'state', 'string'],
    ['country', 'country', 'string'],
    ['industry_id', 'industryId', 'number'],
    ['industry_size_id', 'industrySizeId', 'number'],
    ['website_url', 'websiteUrl', 'string'],
    ['source_id', 'sourceId', 'number'],
    ['referral_name', 'referralName', 'string'],
    ['preferred_lang_id', 'preferredLangId', 'string'],
    ['notes', 'notes', 'string'],
    ['source_by', 'sourceBy', 'number'],
    ['assigned_to', 'assignedTo', 'number'],
    ['assigned_by', 'assignedBy', 'number'],
    ['stage_code', 'stageCode', 'string'],
    ['created_at', 'createdAt', 'date'],
    ['updated_at', 'updatedAt', 'date']
];
