export const messageMapping = [
    ['id', 'templateId', 'number'],
    ['id', 'queueId', 'number'],
    ['template_code', 'templateCode', 'string'],
    ['language_id', 'languageId', 'string'],
    ['channel', 'channel', 'number'],
    ['subject', 'subject', 'string'],
    ['body', 'body', 'string'],
    ['variables', 'variables', 'string'],
    ['prospect_id', 'prospectId', 'number'],
    ['to_address', 'toAddress', 'string'],
    ['status', 'status', 'number'],
    ['retry_count', 'retryCount', 'number'],
    ['locked_at', 'lockedAt', 'date'],
    ['payload', 'payload', 'object'],
    ['error_message', 'errorMessage', 'string'],
    ['worker_id', 'workerId', 'string'],
    ['last_attempt_at', 'lastAttemptAt', 'date'],
    ['sent_at', 'sentAt', 'date'],
    ['isActive', 'isActive', 'number'],
    ['attempt_number', 'attemptNumber', 'number'],
    ['max_attempt_number', 'maxAttemptNumber', 'number'],
    ['created_by', 'createdBy', 'number'],
    ['created_at', 'createdAt', 'date'],
    ['updated_at', 'updatedAt', 'date']
];